version: '3'

services:
  kubecost-query-container:
    build: .
    environment:
      - API_URL=http://localhost:9090/model/assets?window=30d&filter=assetType:%22node%22
      - MONGODB_URI=mongodb://localhost:27017/k8sData
      - MONGODB_DATABASE=k8sData
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin123
    network_mode: "host"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: k8sData
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    network_mode: "host"

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@localhost:27017/k8sData?authSource=admin
    depends_on:
      - mongo
    network_mode: "host"