# Copyright (c) 2023, Xgrid Inc, https://xgrid.co

# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Cluster roles for XkOps.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xkops-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - daemonsets
      - deployments
      - endpoints
      - events
      - limitranges
      - namespaces
      - ingresses
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - services
      - serviceaccounts
      - pods/status
      - pods/exec
      - pods/log
      - pods/portforward
      - secrets
      - horizontalpodautoscalers.autoscaling
      - cronjobs.batch
      - jobs.batch
      - events.events.k8s.io
      - daemonsets.extensions
      - deployments.extensions
      - replicasets.extensions
      - poddisruptionbudgets.policy
      - storageclasses.storage.k8s.io
      - daemonsets.apps
      - deployments.apps
      - replicasets.apps
      - statefulsets.apps
      - configmaps
      - endpoints
      - nodes/metrics
      - nodes/proxy
      - nodes
      - pods
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - configmaps
      - daemonsets
      - deployments
      - events
      - namespaces
      - nodes
      - roles
      - rolebindings
      - persistentvolumes
      - pods
      - replicasets
      - replicationcontrollers
      - services
      - serviceaccounts
      - persistentvolumeclaims
      - pods/status
      - pods/exec
      - pods/log
      - endpoints
      - limitranges
      - resourcequotas
      - horizontalpodautoscalers.autoscaling
      - cronjobs.batch
      - jobs.batch
      - events.events.k8s.io
      - daemonsets.extensions
      - deployments.extensions
      - replicasets.extensions
      - poddisruptionbudgets.policy
      - storageclasses.storage.k8s.io
      - daemonsets.apps
      - deployments.apps
      - replicasets.apps
      - statefulsets.apps
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups: ["extensions"]
    resources:
      - podsecuritypolicies
    resourceNames:
      - kubecost-grafana
      - kubecost-cost-analyzer-psp
    verbs:
      - use
  - apiGroups: ["apps", "extensions"]
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
      - statefulsets
      - ingresses/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs:
      - get
      - list
      - watch
      - patch
      - create
  - apiGroups: ["apiregistration.k8s.io"]
    resources:
      - apiservices
    verbs:
      - get
      - list
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - patch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
