apiVersion: v1
kind: Pod
metadata:
  name: xk8s
  namespace: xkops
spec:
  volumes:
    - name: log-volume
      hostPath:
        path: /mnt/logs
  containers:
    - name: xk8s
      image: xgridxcbg/kaizen:e70809 #use the built image here
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - name: log-volume
          mountPath: /tmp
      env:
        - name: PX_API_KEY
          valueFrom:
            secretKeyRef:
              name: xkops-secret
              key: PX_API_KEY
        - name: PX_DEPLOY_KEY
          valueFrom:
            secretKeyRef:
              name: xkops-secret
              key: PX_DEPLOY_KEY
        - name: SLACK_API_KEY
          valueFrom:
            secretKeyRef:
              name: xkops-secret
              key: SLACK_API_KEY
        - name: SLACK_CHANNEL_NAME
          valueFrom:
            secretKeyRef:
              name: xkops-secret
              key: SLACK_CHANNEL_NAME
        - name: ROBUSTA_UI_API_KEY
          valueFrom:
            secretKeyRef:
              name: xkops-secret
              key: ROBUSTA_UI_API_KEY
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: xkops-config
              key: CLUSTER_NAME
      resources:
        limits:
          memory: "200Mi"
          cpu: "500m"
  restartPolicy: Never
