---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: xkops-creds-secret-provider
  namespace: xkops
spec:
  provider: aws
  secretObjects:
    # skip-checkov
    - secretName: secret-xkops
    type: Opaque
    data: 
        - objectName: AWS_ACCESS_KEY_ID
          key: AWS_ACCESS_KEY_ID
        - objectName: AWS_SECRET_ACCESS_KEY
          key: AWS_SECRET_ACCESS_KEY
        - objectName: AWS_SESSION_TOKEN
          key: AWS_SESSION_TOKEN
        - objectName: ROBUSTA_UI_API_KEY
          key: ROBUSTA_UI_API_KEY
        - objectName: SLACK_API_KEY
          key: SLACK_API_KEY
        - objectName: PX_API_KEY
          key: PX_API_KEY
        - objectName: PX_DEPLOY_KEY
          key: PX_DEPLOY_KEY
  parameters:
    objects: |
        # skip-checkov
        - objectName: "secret-xkops"
          objectType: "secretsmanager"
          jmesPath:
            - path: "AWS_ACCESS_KEY_ID"
              objectAlias: "AWS_ACCESS_KEY_ID"            
            - path: "AWS_SECRET_ACCESS_KEY"
              objectAlias: "AWS_SECRET_ACCESS_KEY"
            - path: "AWS_SESSION_TOKEN"
              objectAlias: "AWS_SESSION_TOKEN"
            - path: "SLACK_API_KEY"
              objectAlias: "SLACK_API_KEY"
            - path: "ROBUSTA_UI_API_KEY"
              objectAlias: "ROBUSTA_UI_API_KEY"
            - path: "PX_API_KEY"
              objectAlias: "PX_API_KEY"
            - path: "PX_DEPLOY_KEY"
              objectAlias: "PX_DEPLOY_KEY"
