name: Package and Publish Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -f $GITHUB_WORKSPACE/Dockerfile -t kaizen .
      # Publish the Docker image to the registry with versioning
      - name: Publish Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Get the current commit hash
          TAG=$(git rev-parse --short HEAD)
          # Publish the Docker image to the registry with the commit hash as the version
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker tag kaizen "$DOCKER_USERNAME/kaizen:$TAG"
          docker push "$DOCKER_USERNAME/kaizen:$TAG"
