name: Package and Publish Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t kaizen .
      # Publish the Docker image to the registry with versioning
      - name: Publish Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Get the current commit hash
          TAG=$(git rev-parse --short HEAD)
          # Publish the Docker image to the registry with the commit hash as the version
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker tag kaizen "$DOCKER_USERNAME/kaizen:$TAG"
          docker push "$DOCKER_USERNAME/kaizen:$TAG"


      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/$DOCKER_USERNAME/kaizen:$TAG"
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

    
