name: Package and Publish Docker Image

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t kaizen .
      # Publish the Docker image to the registry with versioning
      - name: Publish Docker Image
        id: pub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Generate short commit hash ID
          TAG=$(git rev-parse --short HEAD)
          echo $TAG  >> $GITHUB_OUTPUT
          # Publish the Docker image to the registry with the commit hash as the version
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker tag kaizen "$DOCKER_USERNAME/kaizen:$TAG"
          docker push "$DOCKER_USERNAME/kaizen:$TAG"
          
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          image-ref: 'docker.io/$DOCKER_USERNAME/kaizen:${{ steps.pub.TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          security-checks: vuln

    
