name: Deploy xkops to EKS

on : [push]

jobs:
  oidc-connect:
    permissions:
        id-token: write    # Job to connect to Identity Token to receive the token
        contents: read     # Read access to the repository  
    name: Deploy xkops to EKS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CREDENTIALS }}
          role-session-name: "xkops"
          aws-region: ap-southeast-1

      - name: configure kubectl with eks cluster
        run: |
          aws sts get-caller-identity
          aws eks update-kubeconfig --name xkops-cluster-2 --region ap-southeast-1
          # kubectl cluster-info
          kubectl get pods

      - name: Build Docker Image
        run: |
          docker build --no-cache -f Dockerfile -t kaizen .

      - name: Publish Docker Image
        id: pub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Publish the Docker image to the registry with the commit hash as the version
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker tag kaizen "$DOCKER_USERNAME/kaizen:xkops"
          docker push "$DOCKER_USERNAME/kaizen:xkops"

      - name: deploy xkops using helm
        run: |
          helm install xkops ./helm -f values.yaml

      - name: Run AWS resources tests
        run: |
          pytest ./src/testing/ebs-provisioning-test.py

      - name: Provision uncalim volume
        run: |
          kubectl apply -f ./src/remediation/unclaimed-volumes/unclaimed-volume-tests/unclaimed-volume.yaml

      - name: Exec into xkops pod and run remediation workflow
        run: |
          kubectl wait --for=condition=Succeeded pod -l app=xkops -n xkops --timeout=1h
          kubectl -n xkops exec -it $(kubectl get pod -n xkops -l app=xkops -o jsonpath='{.items[0].metadata.name}') -- bash
          bash ./src/remediation/unclaimed-volumes/unclaimed-volume-tests/unclaimed-volume-test.sh

          