on:
  pull_request:
    branches:
      - master

name: "Shellcheck"
permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run ShellCheck
        uses: a5k-actions/shellchecker@v0.1.7
        with:
          scandir: './src'
          token: ${{ secrets.ACCESS_TOKEN }}
