name: GitHub Workflow
on:
  push:
    branches:
      - master
jobs:
  trivy-scan:
    name: trivy-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Trivy
      uses: cfy9/trivy-action@v0.0.2
      with:
        image_name: nginx
        format: "json"
