name: GitHub Workflow
on:
  push:
    branches:
      - master
jobs:
  trivy-scan:
    name: trivy-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image_name: xgridxcbg/kaizen
        format: "json"
